from typing import Any, Dict, List, Optional, Protocol, Sequence, Tuple

from server.features.deep_memory.domain.episodes import Episode
from server.features.deep_memory.domain.structure import FileParse


class StructureStore(Protocol):
    def load(self, project_id: str) -> Dict[str, FileParse]: ...

    def save(self, project_id: str, parse: FileParse) -> None: ...

    def delete(self, project_id: str, path: str) -> None: ...


class DerivedCache(Protocol):
    def get(self, project_id: str, symbol_id: str, key: str) -> Optional[Any]: ...

    def put(self, project_id: str, symbol_id: str, key: str, value: Any, fingerprint: str) -> None: ...

    def drop(self, project_id: str, symbol_ids: Sequence[str]) -> int: ...


class Embedder(Protocol):
    async def embed(self, text: str) -> List[float]: ...


class EpisodeStore(Protocol):
    def add(self, episode: Episode, semantic: Optional[List[float]], lexical: List[float]) -> None: ...

    def all_vectors(self) -> List[Tuple[Episode, Optional[List[float]], List[float]]]: ...

    def mark_resolved(self, episode_id: str, resolution: str) -> bool: ...
