import os
from server.features.sysops_automation.sysops_contracts import AppScaffoldRequest

class ApplicationScaffolder:
    async def scaffold_application(self, req: AppScaffoldRequest) -> bool:
        base_dir = os.path.abspath(os.path.join(req.target_directory, req.app_name))
        os.makedirs(base_dir, exist_ok=True)

        if req.template_type == "fastapi":
            return self._scaffold_fastapi(base_dir, req)
        elif req.template_type == "service":
            return self._scaffold_systemd_service(base_dir, req)
        else:
            return self._scaffold_generic_python(base_dir, req)

    def _scaffold_fastapi(self, target_dir: str, req: AppScaffoldRequest) -> bool:
        main_py = (
            "from fastapi import FastAPI\n\n"
            f"app = FastAPI(title='{req.app_name}')\n\n"
            "@app.get('/')\n"
            "def root():\n"
            f"    return {{'status': 'ONLINE', 'app': '{req.app_name}'}}\n"
        )
        requirements_txt = "fastapi>=0.110.0\nuvicorn>=0.29.0\n"

        with open(os.path.join(target_dir, "main.py"), "w", encoding="utf-8") as f:
            f.write(main_py)
        with open(os.path.join(target_dir, "requirements.txt"), "w", encoding="utf-8") as f:
            f.write(requirements_txt)
        return True

    def _scaffold_systemd_service(self, target_dir: str, req: AppScaffoldRequest) -> bool:
        service_content = (
            "[Unit]\n"
            f"Description={req.app_name} Daemon Managed by Jarvis\n"
            "After=network.target\n\n"
            "[Service]\n"
            "Type=simple\n"
            "Restart=always\n"
            f"WorkingDirectory={target_dir}\n"
            f"ExecStart=/usr/bin/python3 {target_dir}/main.py\n\n"
            "[Install]\n"
            "WantedBy=multi-user.target\n"
        )
        with open(os.path.join(target_dir, f"{req.app_name}.service"), "w", encoding="utf-8") as f:
            f.write(service_content)
        return True

    def _scaffold_generic_python(self, target_dir: str, req: AppScaffoldRequest) -> bool:
        main_py = (
            f"def main():\n"
            f"    print('Initializing {req.app_name} generated by Jarvis.')\n\n"
            "if __name__ == '__main__':\n"
            "    main()\n"
        )
        with open(os.path.join(target_dir, "app.py"), "w", encoding="utf-8") as f:
            f.write(main_py)
        return True

app_scaffolder = ApplicationScaffolder()
